name: Deploy Azure Functions

on:
  push:
    branches:
      - main
    paths:
      - 'azure-functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: azure-functions/package-lock.json

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm ci
        # Build only if build script exists in package.json
        if grep -q '"build"' package.json; then
          npm run build
        fi
        popd

    - name: 'Run Azure Functions Action'
      # Only deploy if Azure secrets are configured
      if: ${{ secrets.AZURE_FUNCTIONAPP_NAME && secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true
    
    - name: 'Skip Deployment Notice'
      if: ${{ !secrets.AZURE_FUNCTIONAPP_NAME || !secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
      run: |
        echo "⚠️  Azure Functions deployment skipped - secrets not configured"
        echo "To enable deployment, configure these repository secrets:"
        echo "  - AZURE_FUNCTIONAPP_NAME"
        echo "  - AZURE_FUNCTIONAPP_PUBLISH_PROFILE"